# Generated by Django 6.0.5 on 2026-06-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom_article', models.CharField(max_length=100)),
                ('preu_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualitat', models.CharField(choices=[('Normal', 'Normal'), ('Bronze', 'Bronze'), ('Plata', 'Plata'), ('Or', 'Or')], max_length=10)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Estacio',
            fields=[
                ('id_estacio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_estacio', models.CharField(choices=[('Primavera', 'Primavera'), ('Estiu', 'Estiu'), ('Tardor', 'Tardor'), ('Hivern', 'Hivern')], max_length=10)),
            ],
            options={
                'db_table': 'estacio',
            },
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id_npc', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('es_solter', models.BooleanField()),
                ('data_aniversari', models.DateField()),
            ],
            options={
                'db_table': 'npc',
            },
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id_usuari', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuari', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('contrasenya', models.CharField(default='1234', max_length=255)),
            ],
            options={
                'db_table': 'usuari',
            },
        ),
        migrations.CreateModel(
            name='Cultiu',
            fields=[
                ('id_article', models.OneToOneField(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.article')),
                ('temps_creixement', models.IntegerField()),
            ],
            options={
                'db_table': 'cultiu',
            },
        ),
        migrations.CreateModel(
            name='Peix',
            fields=[
                ('id_article', models.OneToOneField(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.article')),
                ('ubicacio_pesca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'peix',
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_article', models.OneToOneField(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.article')),
                ('energia_recuperada', models.IntegerField()),
            ],
            options={
                'db_table': 'plat',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False)),
                ('nom_granja', models.CharField(max_length=100)),
                ('nivell_energia', models.IntegerField()),
                ('diners', models.IntegerField(default=500)),
                ('dia', models.IntegerField(default=1)),
                ('estacio_actual', models.ForeignKey(blank=True, db_column='id_estacio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estacio')),
                ('id_usuari', models.ForeignKey(db_column='id_usuari', on_delete=django.db.models.deletion.CASCADE, to='core.usuari')),
            ],
            options={
                'db_table': 'partida',
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('pk', models.CompositePrimaryKey('id_npc', 'id_article', blank=True, editable=False, primary_key=True, serialize=False)),
                ('reaccio', models.CharField(choices=[('Agrada', 'Agrada'), ('Neutral', 'Neutral'), ('Odia', 'Odia')], max_length=10)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('id_npc', models.ForeignKey(db_column='id_npc', on_delete=django.db.models.deletion.CASCADE, to='core.npc')),
            ],
            options={
                'db_table': 'preferencia',
            },
        ),
        migrations.CreateModel(
            name='Regal',
            fields=[
                ('pk', models.CompositePrimaryKey('id_partida', 'id_npc', 'id_article', 'data_regal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_regal', models.DateField()),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('id_npc', models.ForeignKey(db_column='id_npc', on_delete=django.db.models.deletion.CASCADE, to='core.npc')),
                ('id_partida', models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
            options={
                'db_table': 'regal',
            },
        ),
        migrations.CreateModel(
            name='CreixEn',
            fields=[
                ('pk', models.CompositePrimaryKey('id_cultiu', 'id_estacio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_estacio', models.ForeignKey(db_column='id_estacio', on_delete=django.db.models.deletion.CASCADE, to='core.estacio')),
                ('id_cultiu', models.ForeignKey(db_column='id_cultiu', on_delete=django.db.models.deletion.CASCADE, to='core.cultiu')),
            ],
            options={
                'db_table': 'creix_en',
            },
        ),
        migrations.CreateModel(
            name='Llavor',
            fields=[
                ('id_article', models.OneToOneField(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.article')),
                ('preu_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cultiu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llavor', to='core.cultiu')),
            ],
            options={
                'db_table': 'llavor',
            },
        ),
        migrations.CreateModel(
            name='EsPesca',
            fields=[
                ('pk', models.CompositePrimaryKey('id_peix', 'id_estacio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_estacio', models.ForeignKey(db_column='id_estacio', on_delete=django.db.models.deletion.CASCADE, to='core.estacio')),
                ('id_peix', models.ForeignKey(db_column='id_peix', on_delete=django.db.models.deletion.CASCADE, to='core.peix')),
            ],
            options={
                'db_table': 'es_pesca',
            },
        ),
        migrations.CreateModel(
            name='Inventari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=0)),
                ('article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('partida', models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
            options={
                'db_table': 'inventari',
                'unique_together': {('partida', 'article')},
            },
        ),
        migrations.CreateModel(
            name='EspaiCultiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('quantitat_plantada', models.IntegerField(default=0)),
                ('data_plantacio', models.DateField(blank=True, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espais_cultiu', to='core.partida')),
                ('llavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espais_cultiu', to='core.llavor')),
            ],
            options={
                'db_table': 'espai_cultiu',
                'unique_together': {('partida', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('pk', models.CompositePrimaryKey('id_plat', 'id_ingredient', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantitat_necesaria', models.IntegerField()),
                ('id_ingredient', models.ForeignKey(db_column='id_ingredient', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('id_plat', models.ForeignKey(db_column='id_plat', on_delete=django.db.models.deletion.CASCADE, to='core.plat')),
            ],
            options={
                'db_table': 'recepta',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantitat_necesaria__gt', 0)), name='recepta_quantitat_necesaria_check')],
            },
        ),
    ]
