# Generated by Django 6.0.5 on 2026-06-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preu_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esta_plantat', models.BooleanField(default=False)),
                ('cultiu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llavor', to='core.cultiu')),
            ],
        ),
        migrations.CreateModel(
            name='EspaiCultiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espais_cultiu', to='core.partida')),
                ('llavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espais_cultiu', to='core.llavor')),
            ],
            options={
                'unique_together': {('partida', 'numero_parcela')},
            },
        ),
    ]
