# Generated by Django 6.0.5 on 2026-06-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_llavor_espaicultiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llavor',
            name='esta_plantat',
        ),
        migrations.RemoveField(
            model_name='llavor',
            name='id',
        ),
        migrations.AddField(
            model_name='espaicultiu',
            name='data_plantacio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espaicultiu',
            name='quantitat_plantada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llavor',
            name='id_article',
            field=models.OneToOneField(db_column='id_article', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='diners',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usuari',
            name='contrasenya',
            field=models.CharField(default='1234', max_length=255),
        ),
        migrations.AlterModelTable(
            name='espaicultiu',
            table='espai_cultiu',
        ),
        migrations.AlterModelTable(
            name='llavor',
            table='llavor',
        ),
        migrations.CreateModel(
            name='Inventari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=0)),
                ('article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('partida', models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
            options={
                'db_table': 'inventari',
                'unique_together': {('partida', 'article')},
            },
        ),
    ]
