# Generated by Django 6.0.5 on 2026-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_llavor_esta_plantat_remove_llavor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='dia',
            field=models.IntegerField(default=1),
        ),
    ]
